name: 'olist_analytics'
version: '1.0.0'
config-version: 2

profile: 'olist'

model-paths:  ["models"]
seed-paths:   ["seeds"]
test-paths:   ["tests"]
macro-paths:  ["macros"]

target-path:  "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  olist_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
      mart_cohort_retention:
        +materialized: incremental
        +incremental_strategy: merge
